name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

jobs:
  build:
    uses: dancook-socialive/pipeline-poc/.github/workflows/build.yml@main
    with:
      nodeVersion: '14.x'
      artifactName: package
  
  staging:
    if: github.ref == 'refs/heads/main'
    needs: build
    name: "Staging"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: staging

  release:
    if: ${{ github.ref == 'refs/heads/release/release_2.0.0' }}
    needs: build
    name: "Release"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: release

  pat:
    needs: release
    name: "pat"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: pat

  production:
    needs: pat
    name: "Production"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: production
  
  sandbox:
    if: ${{ github.ref == 'refs/heads/release/release_1.0.0' }}
    needs: build
    name: "Sandbox"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: release