name: CI

on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:

env:
  NEXT_RELEASE: 'refs/heads/release/release_2.0.0'
  CURRENT_RELEASE: 'refs/heads/release/release_1.0.0'

jobs:
  build:
    uses: dancook-socialive/pipeline-poc/.github/workflows/build.yml@main
    with:
      nodeVersion: '14.x'
      artifactName: package
  
  staging:
    if: github.ref == 'refs/heads/main'
    needs: build
    name: "Staging"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: staging

  release:
    if: ${{ github.ref == env.NEXT_RELEASE }}
    needs: build
    name: "Release"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: release

  production:
    if: ${{ github.ref == env.NEXT_RELEASE }}
    needs: release
    name: "Production"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: production
  
  sandbox:
    if: ${{ github.ref == env.CURRENT_RELEASE }}
    needs: build
    name: "Release"
    uses: dancook-socialive/pipeline-poc/.github/workflows/deploy.yml@main
    with:
      artifactName: package
      environment: release