name: Deploy to Development

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

jobs:
  deploy:
    name: Deploy to Development
    runs-on: ubuntu-latest
    environment: development

    steps:
    - name: Magic Deploy
      run: echo 'deployed to development'
